import sequelize from "../config/db.js";
import Service from "../models/Service.js";
import ServiceInclusion from "../models/ServiceInclusion.js";

if (process.env.NODE_ENV === "production") {
  console.error(
    "Los seeders no pueden ejecutarse en producción (NODE_ENV=production).",
  );
  process.exit(1);
}

const run = async () => {
  try {
    await sequelize.authenticate();
    console.log(
      "Conectando a la BD para poblar el catálogo COMPLETO de servicios...",
    );

    const servicesData = [
      // ==========================================
      // MODELHA DK (Tratamientos Faciales y Estética)
      // ==========================================
      {
        brand: "Modelha DK",
        name: "Facial Purificante",
        description:
          "Limpieza profunda con limpieza de poro a poro, mejora la textura de la piel, regula el sebo manteniendo la hidratación y luminosidad.",
        suggestedFrequency: "Cada 3 a 4 semanas",
        regularPrice: 650.0,
        promoPrice: 549.5, // Promo 2x1099
        requiresAssessment: false,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "Exfoliación cosmética" },
          { itemName: "Desincrustación" },
          { itemName: "Vapor" },
          { itemName: "Extracción de impurezas" },
          { itemName: "Limpieza" },
          { itemName: "Alta frecuencia" },
          { itemName: "Coctel de acuerdo al tipo de piel" },
          { itemName: "Mascarilla" },
          { itemName: "Hidratación" },
          { itemName: "Protección Solar" },
          { itemName: "Masaje de relajación y aromacosmética" },
        ],
      },
      {
        brand: "Modelha DK",
        name: "Facial Purificante Diamante",
        description:
          "Tiene como objetivo limpiar la piel, mejorar la textura, unificar el tono y reducir los poros visibles, ayuda a una mejor absorción de productos.",
        suggestedFrequency: "Cada 4 semanas",
        regularPrice: 700.0,
        promoPrice: 599.5, // Promo 2x1199
        requiresAssessment: false,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "Microdermoabrasión" },
          { itemName: "Desincrustación" },
          { itemName: "Vapor" },
          { itemName: "Extracción de impurezas" },
          { itemName: "Limpieza" },
          { itemName: "Alta frecuencia" },
          { itemName: "Coctel de acuerdo al tipo de piel" },
          { itemName: "Mascarilla" },
          { itemName: "Hidratación" },
          { itemName: "Protección Solar" },
          { itemName: "Masaje de relajación y aromacosmética" },
        ],
      },
      {
        brand: "Modelha DK",
        name: "Facial con Dermaplaning",
        description:
          "El dermaplaning es un tratamiento no invasivo que exfolia la piel utilizando una hoja de bisturí, elimina células muertas y vello.",
        suggestedFrequency: "Cada 4 semanas",
        regularPrice: 700.0,
        promoPrice: 599.5, // Promo 2x1199
        requiresAssessment: false,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "Dermaplaning" },
          { itemName: "Desincrustación" },
          { itemName: "Vapor" },
          { itemName: "Extracción de impurezas" },
          { itemName: "Limpieza" },
          { itemName: "Alta frecuencia" },
          { itemName: "Coctel de acuerdo al tipo de piel" },
          { itemName: "Mascarilla" },
          { itemName: "Hidratación" },
          { itemName: "Protección Solar" },
          { itemName: "Masaje de relajación y aromacosmética" },
        ],
      },
      {
        brand: "Modelha DK",
        name: "Hydrofacial",
        description:
          "Tratamiento estético avanzado que limpia, exfolia, extrae impurezas e hidrata profundamente en una sola sesión.",
        suggestedFrequency: "Cada 4 semanas",
        regularPrice: 1100.0,
        promoPrice: 949.5, // Promo 2x1899
        requiresAssessment: false,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "Exfoliación" },
          { itemName: "Peeling" },
          { itemName: "Extracción de impurezas" },
          { itemName: "Alta frecuencia" },
          { itemName: "Perfusión" },
          { itemName: "Mascarilla" },
          { itemName: "Hidratación" },
          { itemName: "Protección Solar" },
          { itemName: "Masaje de relajación y aromacosmética" },
        ],
      },
      {
        brand: "Modelha DK",
        name: "Peeling By Mesoestetic",
        description:
          "Procedimiento químico que aplica ácidos para exfoliar la piel y reducir hiperpigmentación.",
        suggestedFrequency: "Cada 4 semanas",
        regularPrice: 900.0,
        promoPrice: 666.33, // Promo 3x1999
        requiresAssessment: true,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "Exfoliación" },
          { itemName: "Peeling" },
          { itemName: "Alta frecuencia" },
          { itemName: "Mascarilla" },
          { itemName: "Hidratación" },
          { itemName: "Protección Solar" },
          { itemName: "Masaje de relajación y aromacosmética" },
        ],
      },
      {
        brand: "Modelha DK",
        name: "Luz Pulsada Facial",
        description:
          "Técnica no ablativa con flashes de luz de amplio espectro para tratar manchas pigmentadas, rojeces y vasos finos.",
        suggestedFrequency: "Cada 4 semanas",
        regularPrice: 600.0,
        promoPrice: 499.75, // Promo 4x1999
        requiresAssessment: true,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "Exfoliación" },
          { itemName: "Luz pulsada" },
          { itemName: "Ultrasonido con glutatión" },
          { itemName: "Mascarilla" },
          { itemName: "Hidratación" },
          { itemName: "Protección Solar" },
          { itemName: "Masaje de relajación y aromacosmética" },
        ],
      },
      {
        brand: "Modelha DK",
        name: "Aclarante By Credentials",
        description:
          "Tratamiento ideal para pieles ultra tratadas por láser o peelings. Calma, regenera y aclara la piel sin irritar.",
        suggestedFrequency: "Semanal (6 sesiones)",
        regularPrice: 780.0,
        promoPrice: null,
        requiresAssessment: true,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "Exfoliación" },
          { itemName: "Dermaplaning" },
          { itemName: "Ultrasonido" },
          { itemName: "Coctel" },
          { itemName: "Crema peeling" },
          { itemName: "Mascarilla" },
          { itemName: "Hidratación" },
          { itemName: "Protección Solar" },
          { itemName: "Masaje de relajación y aromacosmética" },
        ],
      },
      {
        brand: "Modelha DK",
        name: "Despigmentante By DK",
        description:
          "Consta de un micropeeling + ampolletas especializadas de Mesoestetic + mascarilla hidratante.",
        suggestedFrequency: "Semanal (4 a 6 sesiones)",
        regularPrice: 1799.0,
        promoPrice: null,
        requiresAssessment: true,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "Exfoliación" },
          { itemName: "Dermaplaning" },
          { itemName: "Peeling" },
          { itemName: "Ultrasonido" },
          { itemName: "Serum + coctel" },
          { itemName: "FotoAge + Lumixa" },
          { itemName: "Mascarilla" },
          { itemName: "Hidratación" },
          { itemName: "Protección Solar" },
          { itemName: "Masaje de relajación" },
        ],
      },
      {
        brand: "Modelha DK",
        name: "Microneedling",
        description:
          "Combo perfecto para aclarar y despigmentar sin dañar la piel con Dermapen, ampolletas y FotoAge.",
        suggestedFrequency: "Semanal (4 a 6 sesiones)",
        regularPrice: 1499.0,
        promoPrice: null,
        requiresAssessment: true,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "Exfoliación" },
          { itemName: "Dermaplaning" },
          { itemName: "Peeling" },
          { itemName: "Ultrasonido + dermia" },
          { itemName: "Dermapen + Ampolleta" },
          { itemName: "FotoAge + Lumixa" },
          { itemName: "Mascarilla" },
          { itemName: "Hidratación" },
          { itemName: "Protección Solar" },
          { itemName: "Masaje de relajación" },
        ],
      },
      {
        brand: "Modelha DK",
        name: "PB Serum Radiant",
        description:
          "Revierte el daño de la radiación, revitaliza la piel apagada, pigmentada y líneas de expresión.",
        suggestedFrequency: "Semanal (4 a 6 sesiones)",
        regularPrice: 1799.0,
        promoPrice: null,
        requiresAssessment: true,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "Exfoliación" },
          { itemName: "Dermaplaning" },
          { itemName: "Peeling" },
          { itemName: "Ultrasonido + dermia" },
          { itemName: "Dermapen + PbSerum" },
          { itemName: "FotoAge + Lumixa" },
          { itemName: "Mascarilla" },
          { itemName: "Hidratación" },
          { itemName: "Protección Solar" },
        ],
      },
      {
        brand: "Modelha DK",
        name: "Skinox Dark Spots + FotoAge",
        description:
          "Tratamiento fotosensible que se activa con luz HDD verde. Terapia fotobiodinámica para regenerar la piel.",
        suggestedFrequency: "Semanal (4 sesiones)",
        regularPrice: 1799.0,
        promoPrice: null,
        requiresAssessment: true,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "Exfoliación" },
          { itemName: "Dermaplaning" },
          { itemName: "Peeling" },
          { itemName: "Ultrasonido + dermia" },
          { itemName: "FotoAge + Serum SkinOX Darkspot" },
          { itemName: "Mascarilla Glutatión" },
          { itemName: "Hidratación" },
          { itemName: "Protección Solar" },
        ],
      },
      {
        brand: "Modelha DK",
        name: "Kontrol Acné By DK",
        description:
          "Tratamiento antibacterial, astringente y secante desincrustante. Mejora la piel sin dañar la barrera cutánea.",
        suggestedFrequency: "Semanal (6 sesiones)",
        regularPrice: 900.0,
        promoPrice: null,
        requiresAssessment: true,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "Exfoliación SkinScrubber" },
          { itemName: "Desincrustación" },
          { itemName: "Vapor" },
          { itemName: "Extracción" },
          { itemName: "Alta Frecuencia" },
          { itemName: "Coctel + Micropeel" },
          { itemName: "Mascarilla" },
          { itemName: "Hidratación" },
          { itemName: "Protección Solar" },
        ],
      },
      {
        brand: "Modelha DK",
        name: "Kontrol Acné By Mesoestetic",
        description:
          "Método intensivo para acné de grado II-III. Disminuye brotes, seborrea e inflamación.",
        suggestedFrequency: "1 vez al mes",
        regularPrice: 900.0,
        promoPrice: null,
        requiresAssessment: true,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "Exfoliación SkinScrubber" },
          { itemName: "Peeling" },
          { itemName: "Mascarilla" },
          { itemName: "Hidratación" },
          { itemName: "Protección Solar" },
        ],
      },
      {
        brand: "Modelha DK",
        name: "Skinox Blemish + FotoAge",
        description:
          "Protocolo dermocosmético para pieles con tendencia acneica e imperfecciones con fotobiomodulación.",
        suggestedFrequency: "1 vez al mes (4 sesiones)",
        regularPrice: 1900.0,
        promoPrice: null,
        requiresAssessment: true,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "Exfoliación SkinScrubber" },
          { itemName: "Peeling" },
          { itemName: "FotoAge + SkinOx Blemish" },
          { itemName: "Mascarilla" },
          { itemName: "Hidratación" },
          { itemName: "Protección Solar" },
        ],
      },
      {
        brand: "Modelha DK",
        name: "Skinox Redness + FotoAge",
        description:
          "Tratamiento fotobiodinámico para estimular, regenerar y reparar la piel con rojeces o rosácea.",
        suggestedFrequency: "1 vez al mes",
        regularPrice: 1900.0,
        promoPrice: null,
        requiresAssessment: true,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "Peeling" },
          { itemName: "Ultrasonido" },
          { itemName: "FotoAge + SkinOx Redness Serum" },
          { itemName: "Mascarilla" },
          { itemName: "Hidratación" },
          { itemName: "Protección Solar" },
        ],
      },
      {
        brand: "Modelha DK",
        name: "Desensibilizante",
        description:
          "Diseñado para calmar, hidratar y fortalecer pieles reactivas, sensibles o con rosácea.",
        suggestedFrequency: "1 vez al mes",
        regularPrice: 650.0,
        promoPrice: null,
        requiresAssessment: true,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "Exfoliación" },
          { itemName: "Peeling" },
          { itemName: "Ultrasonido" },
          { itemName: "Coctel" },
          { itemName: "Mascarilla" },
          { itemName: "Hidratación" },
          { itemName: "Protección Solar" },
        ],
      },
      {
        brand: "Modelha DK",
        name: "Radiofrecuencia Facial",
        description:
          "Energía electromagnética que calienta las capas profundas para reafirmar y estimular colágeno.",
        suggestedFrequency: "1 vez por semana (6-8 sesiones)",
        regularPrice: 550.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "Exfoliación" },
          { itemName: "Peeling" },
          { itemName: "Ultrasonido con ampolleta" },
          { itemName: "Radiofrecuencia" },
          { itemName: "Mascarilla" },
          { itemName: "Masaje circulatorio + hidratante" },
          { itemName: "Protección Solar" },
        ],
      },
      {
        brand: "Modelha DK",
        name: "Antiage Rejuvenecedor",
        description:
          "Tonifica, atenúa líneas de expresión y músculos del rostro con un shot extra de hidratación.",
        suggestedFrequency: "1 vez por semana (6 sesiones)",
        regularPrice: 650.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "Exfoliación" },
          { itemName: "Peeling" },
          { itemName: "Ultrasonido con ampolleta" },
          { itemName: "Reverse" },
          { itemName: "Mascarilla" },
          { itemName: "Masaje circulatorio" },
          { itemName: "Protección Solar" },
        ],
      },
      {
        brand: "Modelha DK",
        name: "BioRePeel",
        description:
          "Peeling médico-estético bifásico innovador para bioestimulación y exfoliación profunda sin descamación.",
        suggestedFrequency: "Cada 10 días (1 a 6 sesiones)",
        regularPrice: 2000.0,
        promoPrice: null,
        requiresAssessment: true,
        isActive: true,
        inclusions: [
          { itemName: "Aromaterapia" },
          { itemName: "Higiene de la piel" },
          { itemName: "BioRePeel" },
          { itemName: "Dermapen" },
          { itemName: "FotoAge" },
          { itemName: "Mascarilla" },
          { itemName: "Masaje circulatorio" },
          { itemName: "Protección Solar" },
        ],
      },

      // ==========================================
      // DEPILCLINIK (Láser - Todas las Áreas)
      // ==========================================
      // --- ÁREAS EXTRA CHICAS ---
      {
        brand: "Depilclinik",
        name: "Entrecejo",
        description: "Depilación TriLáser zona entrecejo.",
        suggestedFrequency: "Mensual",
        regularPrice: 380.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Nariz",
        description: "Depilación TriLáser zona nasal.",
        suggestedFrequency: "Mensual",
        regularPrice: 390.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Pómulos",
        description: "Depilación TriLáser en pómulos.",
        suggestedFrequency: "Mensual",
        regularPrice: 280.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Mentón",
        description: "Depilación TriLáser en mentón.",
        suggestedFrequency: "Mensual",
        regularPrice: 380.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Orejas",
        description: "Depilación TriLáser en orejas.",
        suggestedFrequency: "Mensual",
        regularPrice: 300.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Patillas",
        description: "Depilación TriLáser en patillas.",
        suggestedFrequency: "Mensual",
        regularPrice: 410.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Pezones",
        description: "Depilación TriLáser en zona de pezones.",
        suggestedFrequency: "Mensual",
        regularPrice: 380.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Bozo",
        description: "Depilación TriLáser en bozo / labio superior.",
        suggestedFrequency: "Mensual",
        regularPrice: 320.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },

      // --- ÁREAS CHICAS Y MEDIANAS ---
      {
        brand: "Depilclinik",
        name: "Medio Rostro",
        description: "Depilación TriLáser en medio rostro.",
        suggestedFrequency: "Mensual",
        regularPrice: 510.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Mejillas",
        description: "Depilación TriLáser en mejillas.",
        suggestedFrequency: "Mensual",
        regularPrice: 450.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Cuello",
        description: "Depilación TriLáser en cuello.",
        suggestedFrequency: "Mensual",
        regularPrice: 600.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Nuca",
        description: "Depilación TriLáser en nuca.",
        suggestedFrequency: "Mensual",
        regularPrice: 500.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Axilas",
        description: "Depilación TriLáser en ambas axilas.",
        suggestedFrequency: "Mensual",
        regularPrice: 460.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Hombro",
        description: "Depilación TriLáser en hombros.",
        suggestedFrequency: "Mensual",
        regularPrice: 400.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Pecho Femenino",
        description: "Depilación TriLáser en pecho femenino.",
        suggestedFrequency: "Mensual",
        regularPrice: 580.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Manos",
        description: "Depilación TriLáser en ambas manos.",
        suggestedFrequency: "Mensual",
        regularPrice: 400.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Línea de Abdomen",
        description: "Depilación TriLáser en línea de abdomen.",
        suggestedFrequency: "Mensual",
        regularPrice: 400.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Bikini Sencillo",
        description: "Depilación TriLáser en bikini sencillo.",
        suggestedFrequency: "Mensual",
        regularPrice: 600.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Línea Interglútea",
        description: "Depilación TriLáser en línea interglútea.",
        suggestedFrequency: "Mensual",
        regularPrice: 440.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Muslo",
        description: "Depilación TriLáser en muslos.",
        suggestedFrequency: "Mensual",
        regularPrice: 450.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Pies",
        description: "Depilación TriLáser en ambos pies.",
        suggestedFrequency: "Mensual",
        regularPrice: 400.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Rostro Completo",
        description: "Depilación TriLáser en rostro completo.",
        suggestedFrequency: "Mensual",
        regularPrice: 700.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Medio Brazo",
        description: "Depilación TriLáser en 1/2 brazo.",
        suggestedFrequency: "Mensual",
        regularPrice: 770.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Medio Abdomen",
        description: "Depilación TriLáser en 1/2 abdomen.",
        suggestedFrequency: "Mensual",
        regularPrice: 700.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Media Espalda",
        description: "Depilación TriLáser en 1/2 espalda.",
        suggestedFrequency: "Mensual",
        regularPrice: 700.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Pecho Masculino",
        description: "Depilación TriLáser en pecho masculino.",
        suggestedFrequency: "Mensual",
        regularPrice: 760.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Bikini Brasileño",
        description: "Depilación TriLáser en bikini brasileño.",
        suggestedFrequency: "Mensual",
        regularPrice: 750.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Cóccix",
        description: "Depilación TriLáser en cóccix.",
        suggestedFrequency: "Mensual",
        regularPrice: 600.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Glúteos",
        description: "Depilación TriLáser en glúteos completos.",
        suggestedFrequency: "Mensual",
        regularPrice: 650.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Femoral",
        description: "Depilación TriLáser en zona femoral.",
        suggestedFrequency: "Mensual",
        regularPrice: 650.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Media Pierna",
        description: "Depilación TriLáser en 1/2 pierna.",
        suggestedFrequency: "Mensual",
        regularPrice: 860.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },

      // --- ÁREAS GRANDES ---
      {
        brand: "Depilclinik",
        name: "Torso",
        description: "Depilación TriLáser en torso completo.",
        suggestedFrequency: "Mensual",
        regularPrice: 900.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Piernas Completas",
        description: "Depilación TriLáser en piernas completas.",
        suggestedFrequency: "Mensual",
        regularPrice: 1050.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Brazo Completo",
        description: "Depilación TriLáser en brazos completos.",
        suggestedFrequency: "Mensual",
        regularPrice: 900.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Espalda Completa",
        description: "Depilación TriLáser en espalda completa.",
        suggestedFrequency: "Mensual",
        regularPrice: 950.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
      {
        brand: "Depilclinik",
        name: "Full Body",
        description: "Depilación TriLáser cuerpo entero completo.",
        suggestedFrequency: "Mensual",
        regularPrice: 4962.0,
        promoPrice: null,
        requiresAssessment: false,
        isActive: true,
        inclusions: [],
      },
    ];

    for (const serviceData of servicesData) {
      const existingService = await Service.findOne({
        where: { name: serviceData.name, brand: serviceData.brand },
      });

      if (existingService) {
        // Actualiza el servicio y sus valores si ya existía la versión recortada
        await existingService.update(serviceData);
        console.log(
          `✔ Actualizado: ${serviceData.name} [${serviceData.brand}]`,
        );
        continue;
      }

      await Service.create(serviceData, {
        include: [{ model: ServiceInclusion, as: "inclusions" }],
      });

      console.log(
        `✔ Creado completo: ${serviceData.name} [${serviceData.brand}]`,
      );
    }

    console.log("\n--- ¡Catálogo COMPLETO insertado exitosamente! ---");
    process.exit(0);
  } catch (error) {
    console.error("Error al poblar el catálogo de servicios:", error);
    process.exit(1);
  }
};

run();
